export const api_config = {
  BASE_URL: "https://training.tamkeen-dev.com/tamkeenstore/public/api",

  ENDPOINTS: {
    LOGIN: "/login",
    VERIFY: "/verify",
    REGISTER: "/register",
    RESEND: "/resend",
    PROFILE: "/customer",
    UPDATE_PROFILE: "/customer",
    CONTACT: "/contact",
    ORDERS: "/order",
    ORDER_DETAILS: "/order/",
    ADD_FAVORITE: "/favorite",
    SHOW_FAVORITE: "/favorite",
    REMOVE_FAVORITE: "/favorite/",
    GET_ALL_CATEGORIES: "/category",  
    GET_CATEGORY_DETAILS: "/category/",
    PRODUCTS: "/product",
    PRODUCT_DETAILS:"/product/",
    GET_CART: "/cart",
    ADD_CART:"/cart",
    REMOVE_CART:"/cart/",
    GET_ADDRESS: "/address",
    ADD_ADDRESS: "/address",
    EDIT_ADDRESS:"/address/",
    DELETE_ADDRESS: "/address/",
    PLACE_ORDER: "/order",
    PRIVACY_POLICY: "/setting/privacy_policy",
    TERMS_CONDITIONS: "/setting/terms_and_conditions",
    PRODUCT_VARIANT: "/product-variant",
    NOTIFICATIONS:"/notification",
    SLIDER: "/slider",
  },
};
